version: '3'

services:
  api:
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
      - .:/src
    ports:
      - 3000:3000

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass password
volumes:
  redis:
    driver: local